
version: '3.7'
services:
  flask-app:
    image: tinokingstone/plugx69:latest
    build: .
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment:
      - DATABASE_URI=mysql+pymysql://root:password@mysqlx69:3306/flaskapp
      - SECRET_KEY=ABCD
        #network: plugx69
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
      #network: plugx69
  db:
    image: tinokingstone/mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
        #network: plugx69
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
